# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

require 'google/protobuf' 


descriptor_data = "\n\rmessage.proto\x12\x04info\"I\n\x07Message\x12\x1c\n\x06\x64\x65mand\x18\x01 \x01(\x0e\x32\x0c.info.Demand\x12 \n\x08response\x18\x02 \x01(\x0e\x32\x0e.info.Response*\x1d\n\x06\x44\x65mand\x12\t\n\x05\x43PCTY\x10\x00\x12\x08\n\x04STRT\x10\x01*\x1c\n\x08Response\x12\x07\n\x03YEP\x10\x00\x12\x07\n\x03NOP\x10\x01\x42 \n\x10\x63omm.struct.infoB\x0cMessageProtob\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Info
  Message = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("info.Message").msgclass
  Demand = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("info.Demand").enummodule
  Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("info.Response").enummodule
end
