// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: capacity.proto
// Protobuf Java Version: 4.29.1

package comm.struct.info;

public final class CapacityProto {
  private CapacityProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      CapacityProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CapacityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:info.Capacity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 serverX_status = 1;</code>
     * @return The serverXStatus.
     */
    int getServerXStatus();

    /**
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <pre>
     * Sayısal server_id
     * </pre>
     *
     * <code>int32 server_id = 3;</code>
     * @return The serverId.
     */
    int getServerId();
  }
  /**
   * Protobuf type {@code info.Capacity}
   */
  public static final class Capacity extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:info.Capacity)
      CapacityOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 1,
        /* suffix= */ "",
        Capacity.class.getName());
    }
    // Use Capacity.newBuilder() to construct.
    private Capacity(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Capacity() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return comm.struct.info.CapacityProto.internal_static_info_Capacity_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return comm.struct.info.CapacityProto.internal_static_info_Capacity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              comm.struct.info.CapacityProto.Capacity.class, comm.struct.info.CapacityProto.Capacity.Builder.class);
    }

    public static final int SERVERX_STATUS_FIELD_NUMBER = 1;
    private int serverXStatus_ = 0;
    /**
     * <code>int32 serverX_status = 1;</code>
     * @return The serverXStatus.
     */
    @java.lang.Override
    public int getServerXStatus() {
      return serverXStatus_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_ = 0L;
    /**
     * <code>int64 timestamp = 2;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int SERVER_ID_FIELD_NUMBER = 3;
    private int serverId_ = 0;
    /**
     * <pre>
     * Sayısal server_id
     * </pre>
     *
     * <code>int32 server_id = 3;</code>
     * @return The serverId.
     */
    @java.lang.Override
    public int getServerId() {
      return serverId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (serverXStatus_ != 0) {
        output.writeInt32(1, serverXStatus_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(2, timestamp_);
      }
      if (serverId_ != 0) {
        output.writeInt32(3, serverId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (serverXStatus_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, serverXStatus_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timestamp_);
      }
      if (serverId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, serverId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof comm.struct.info.CapacityProto.Capacity)) {
        return super.equals(obj);
      }
      comm.struct.info.CapacityProto.Capacity other = (comm.struct.info.CapacityProto.Capacity) obj;

      if (getServerXStatus()
          != other.getServerXStatus()) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (getServerId()
          != other.getServerId()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVERX_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getServerXStatus();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + SERVER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getServerId();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static comm.struct.info.CapacityProto.Capacity parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static comm.struct.info.CapacityProto.Capacity parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static comm.struct.info.CapacityProto.Capacity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static comm.struct.info.CapacityProto.Capacity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static comm.struct.info.CapacityProto.Capacity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static comm.struct.info.CapacityProto.Capacity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static comm.struct.info.CapacityProto.Capacity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static comm.struct.info.CapacityProto.Capacity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static comm.struct.info.CapacityProto.Capacity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static comm.struct.info.CapacityProto.Capacity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static comm.struct.info.CapacityProto.Capacity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static comm.struct.info.CapacityProto.Capacity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(comm.struct.info.CapacityProto.Capacity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code info.Capacity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:info.Capacity)
        comm.struct.info.CapacityProto.CapacityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return comm.struct.info.CapacityProto.internal_static_info_Capacity_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return comm.struct.info.CapacityProto.internal_static_info_Capacity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                comm.struct.info.CapacityProto.Capacity.class, comm.struct.info.CapacityProto.Capacity.Builder.class);
      }

      // Construct using comm.struct.info.CapacityProto.Capacity.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        serverXStatus_ = 0;
        timestamp_ = 0L;
        serverId_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return comm.struct.info.CapacityProto.internal_static_info_Capacity_descriptor;
      }

      @java.lang.Override
      public comm.struct.info.CapacityProto.Capacity getDefaultInstanceForType() {
        return comm.struct.info.CapacityProto.Capacity.getDefaultInstance();
      }

      @java.lang.Override
      public comm.struct.info.CapacityProto.Capacity build() {
        comm.struct.info.CapacityProto.Capacity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public comm.struct.info.CapacityProto.Capacity buildPartial() {
        comm.struct.info.CapacityProto.Capacity result = new comm.struct.info.CapacityProto.Capacity(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(comm.struct.info.CapacityProto.Capacity result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.serverXStatus_ = serverXStatus_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.timestamp_ = timestamp_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.serverId_ = serverId_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof comm.struct.info.CapacityProto.Capacity) {
          return mergeFrom((comm.struct.info.CapacityProto.Capacity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(comm.struct.info.CapacityProto.Capacity other) {
        if (other == comm.struct.info.CapacityProto.Capacity.getDefaultInstance()) return this;
        if (other.getServerXStatus() != 0) {
          setServerXStatus(other.getServerXStatus());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.getServerId() != 0) {
          setServerId(other.getServerId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                serverXStatus_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                timestamp_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                serverId_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int serverXStatus_ ;
      /**
       * <code>int32 serverX_status = 1;</code>
       * @return The serverXStatus.
       */
      @java.lang.Override
      public int getServerXStatus() {
        return serverXStatus_;
      }
      /**
       * <code>int32 serverX_status = 1;</code>
       * @param value The serverXStatus to set.
       * @return This builder for chaining.
       */
      public Builder setServerXStatus(int value) {

        serverXStatus_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 serverX_status = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerXStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverXStatus_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 2;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 2;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {

        timestamp_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private int serverId_ ;
      /**
       * <pre>
       * Sayısal server_id
       * </pre>
       *
       * <code>int32 server_id = 3;</code>
       * @return The serverId.
       */
      @java.lang.Override
      public int getServerId() {
        return serverId_;
      }
      /**
       * <pre>
       * Sayısal server_id
       * </pre>
       *
       * <code>int32 server_id = 3;</code>
       * @param value The serverId to set.
       * @return This builder for chaining.
       */
      public Builder setServerId(int value) {

        serverId_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Sayısal server_id
       * </pre>
       *
       * <code>int32 server_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        serverId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:info.Capacity)
    }

    // @@protoc_insertion_point(class_scope:info.Capacity)
    private static final comm.struct.info.CapacityProto.Capacity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new comm.struct.info.CapacityProto.Capacity();
    }

    public static comm.struct.info.CapacityProto.Capacity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Capacity>
        PARSER = new com.google.protobuf.AbstractParser<Capacity>() {
      @java.lang.Override
      public Capacity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Capacity> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Capacity> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public comm.struct.info.CapacityProto.Capacity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_Capacity_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_info_Capacity_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016capacity.proto\022\004info\"H\n\010Capacity\022\026\n\016se" +
      "rverX_status\030\001 \001(\005\022\021\n\ttimestamp\030\002 \001(\003\022\021\n" +
      "\tserver_id\030\003 \001(\005B!\n\020comm.struct.infoB\rCa" +
      "pacityProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_info_Capacity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_info_Capacity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_info_Capacity_descriptor,
        new java.lang.String[] { "ServerXStatus", "Timestamp", "ServerId", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
