// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: message.proto
// Protobuf Java Version: 4.29.1

package comm.struct.info;

public final class MessageProto {
  private MessageProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      MessageProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code info.Demand}
   */
  public enum Demand
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CPCTY = 0;</code>
     */
    CPCTY(0),
    /**
     * <code>STRT = 1;</code>
     */
    STRT(1),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 1,
        /* suffix= */ "",
        Demand.class.getName());
    }
    /**
     * <code>CPCTY = 0;</code>
     */
    public static final int CPCTY_VALUE = 0;
    /**
     * <code>STRT = 1;</code>
     */
    public static final int STRT_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Demand valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Demand forNumber(int value) {
      switch (value) {
        case 0: return CPCTY;
        case 1: return STRT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Demand>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Demand> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Demand>() {
            public Demand findValueByNumber(int number) {
              return Demand.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return comm.struct.info.MessageProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final Demand[] VALUES = values();

    public static Demand valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Demand(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:info.Demand)
  }

  /**
   * Protobuf enum {@code info.Response}
   */
  public enum Response
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>YEP = 0;</code>
     */
    YEP(0),
    /**
     * <code>NOP = 1;</code>
     */
    NOP(1),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 1,
        /* suffix= */ "",
        Response.class.getName());
    }
    /**
     * <code>YEP = 0;</code>
     */
    public static final int YEP_VALUE = 0;
    /**
     * <code>NOP = 1;</code>
     */
    public static final int NOP_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Response valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Response forNumber(int value) {
      switch (value) {
        case 0: return YEP;
        case 1: return NOP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Response>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Response> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Response>() {
            public Response findValueByNumber(int number) {
              return Response.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return comm.struct.info.MessageProto.getDescriptor().getEnumTypes().get(1);
    }

    private static final Response[] VALUES = values();

    public static Response valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Response(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:info.Response)
  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:info.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.info.Demand demand = 1;</code>
     * @return The enum numeric value on the wire for demand.
     */
    int getDemandValue();
    /**
     * <code>.info.Demand demand = 1;</code>
     * @return The demand.
     */
    comm.struct.info.MessageProto.Demand getDemand();

    /**
     * <code>.info.Response response = 2;</code>
     * @return The enum numeric value on the wire for response.
     */
    int getResponseValue();
    /**
     * <code>.info.Response response = 2;</code>
     * @return The response.
     */
    comm.struct.info.MessageProto.Response getResponse();
  }
  /**
   * Protobuf type {@code info.Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:info.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 1,
        /* suffix= */ "",
        Message.class.getName());
    }
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      demand_ = 0;
      response_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return comm.struct.info.MessageProto.internal_static_info_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return comm.struct.info.MessageProto.internal_static_info_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              comm.struct.info.MessageProto.Message.class, comm.struct.info.MessageProto.Message.Builder.class);
    }

    public static final int DEMAND_FIELD_NUMBER = 1;
    private int demand_ = 0;
    /**
     * <code>.info.Demand demand = 1;</code>
     * @return The enum numeric value on the wire for demand.
     */
    @java.lang.Override public int getDemandValue() {
      return demand_;
    }
    /**
     * <code>.info.Demand demand = 1;</code>
     * @return The demand.
     */
    @java.lang.Override public comm.struct.info.MessageProto.Demand getDemand() {
      comm.struct.info.MessageProto.Demand result = comm.struct.info.MessageProto.Demand.forNumber(demand_);
      return result == null ? comm.struct.info.MessageProto.Demand.UNRECOGNIZED : result;
    }

    public static final int RESPONSE_FIELD_NUMBER = 2;
    private int response_ = 0;
    /**
     * <code>.info.Response response = 2;</code>
     * @return The enum numeric value on the wire for response.
     */
    @java.lang.Override public int getResponseValue() {
      return response_;
    }
    /**
     * <code>.info.Response response = 2;</code>
     * @return The response.
     */
    @java.lang.Override public comm.struct.info.MessageProto.Response getResponse() {
      comm.struct.info.MessageProto.Response result = comm.struct.info.MessageProto.Response.forNumber(response_);
      return result == null ? comm.struct.info.MessageProto.Response.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (demand_ != comm.struct.info.MessageProto.Demand.CPCTY.getNumber()) {
        output.writeEnum(1, demand_);
      }
      if (response_ != comm.struct.info.MessageProto.Response.YEP.getNumber()) {
        output.writeEnum(2, response_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (demand_ != comm.struct.info.MessageProto.Demand.CPCTY.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, demand_);
      }
      if (response_ != comm.struct.info.MessageProto.Response.YEP.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, response_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof comm.struct.info.MessageProto.Message)) {
        return super.equals(obj);
      }
      comm.struct.info.MessageProto.Message other = (comm.struct.info.MessageProto.Message) obj;

      if (demand_ != other.demand_) return false;
      if (response_ != other.response_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEMAND_FIELD_NUMBER;
      hash = (53 * hash) + demand_;
      hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + response_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static comm.struct.info.MessageProto.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static comm.struct.info.MessageProto.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static comm.struct.info.MessageProto.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static comm.struct.info.MessageProto.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static comm.struct.info.MessageProto.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static comm.struct.info.MessageProto.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static comm.struct.info.MessageProto.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static comm.struct.info.MessageProto.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static comm.struct.info.MessageProto.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static comm.struct.info.MessageProto.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static comm.struct.info.MessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static comm.struct.info.MessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(comm.struct.info.MessageProto.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code info.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:info.Message)
        comm.struct.info.MessageProto.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return comm.struct.info.MessageProto.internal_static_info_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return comm.struct.info.MessageProto.internal_static_info_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                comm.struct.info.MessageProto.Message.class, comm.struct.info.MessageProto.Message.Builder.class);
      }

      // Construct using comm.struct.info.MessageProto.Message.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        demand_ = 0;
        response_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return comm.struct.info.MessageProto.internal_static_info_Message_descriptor;
      }

      @java.lang.Override
      public comm.struct.info.MessageProto.Message getDefaultInstanceForType() {
        return comm.struct.info.MessageProto.Message.getDefaultInstance();
      }

      @java.lang.Override
      public comm.struct.info.MessageProto.Message build() {
        comm.struct.info.MessageProto.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public comm.struct.info.MessageProto.Message buildPartial() {
        comm.struct.info.MessageProto.Message result = new comm.struct.info.MessageProto.Message(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(comm.struct.info.MessageProto.Message result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.demand_ = demand_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.response_ = response_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof comm.struct.info.MessageProto.Message) {
          return mergeFrom((comm.struct.info.MessageProto.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(comm.struct.info.MessageProto.Message other) {
        if (other == comm.struct.info.MessageProto.Message.getDefaultInstance()) return this;
        if (other.demand_ != 0) {
          setDemandValue(other.getDemandValue());
        }
        if (other.response_ != 0) {
          setResponseValue(other.getResponseValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                demand_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                response_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int demand_ = 0;
      /**
       * <code>.info.Demand demand = 1;</code>
       * @return The enum numeric value on the wire for demand.
       */
      @java.lang.Override public int getDemandValue() {
        return demand_;
      }
      /**
       * <code>.info.Demand demand = 1;</code>
       * @param value The enum numeric value on the wire for demand to set.
       * @return This builder for chaining.
       */
      public Builder setDemandValue(int value) {
        demand_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.info.Demand demand = 1;</code>
       * @return The demand.
       */
      @java.lang.Override
      public comm.struct.info.MessageProto.Demand getDemand() {
        comm.struct.info.MessageProto.Demand result = comm.struct.info.MessageProto.Demand.forNumber(demand_);
        return result == null ? comm.struct.info.MessageProto.Demand.UNRECOGNIZED : result;
      }
      /**
       * <code>.info.Demand demand = 1;</code>
       * @param value The demand to set.
       * @return This builder for chaining.
       */
      public Builder setDemand(comm.struct.info.MessageProto.Demand value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        demand_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.info.Demand demand = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDemand() {
        bitField0_ = (bitField0_ & ~0x00000001);
        demand_ = 0;
        onChanged();
        return this;
      }

      private int response_ = 0;
      /**
       * <code>.info.Response response = 2;</code>
       * @return The enum numeric value on the wire for response.
       */
      @java.lang.Override public int getResponseValue() {
        return response_;
      }
      /**
       * <code>.info.Response response = 2;</code>
       * @param value The enum numeric value on the wire for response to set.
       * @return This builder for chaining.
       */
      public Builder setResponseValue(int value) {
        response_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.info.Response response = 2;</code>
       * @return The response.
       */
      @java.lang.Override
      public comm.struct.info.MessageProto.Response getResponse() {
        comm.struct.info.MessageProto.Response result = comm.struct.info.MessageProto.Response.forNumber(response_);
        return result == null ? comm.struct.info.MessageProto.Response.UNRECOGNIZED : result;
      }
      /**
       * <code>.info.Response response = 2;</code>
       * @param value The response to set.
       * @return This builder for chaining.
       */
      public Builder setResponse(comm.struct.info.MessageProto.Response value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        response_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.info.Response response = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponse() {
        bitField0_ = (bitField0_ & ~0x00000002);
        response_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:info.Message)
    }

    // @@protoc_insertion_point(class_scope:info.Message)
    private static final comm.struct.info.MessageProto.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new comm.struct.info.MessageProto.Message();
    }

    public static comm.struct.info.MessageProto.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public comm.struct.info.MessageProto.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_info_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_info_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\004info\"I\n\007Message\022\034\n\006dema" +
      "nd\030\001 \001(\0162\014.info.Demand\022 \n\010response\030\002 \001(\016" +
      "2\016.info.Response*\035\n\006Demand\022\t\n\005CPCTY\020\000\022\010\n" +
      "\004STRT\020\001*\034\n\010Response\022\007\n\003YEP\020\000\022\007\n\003NOP\020\001B \n" +
      "\020comm.struct.infoB\014MessageProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_info_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_info_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_info_Message_descriptor,
        new java.lang.String[] { "Demand", "Response", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
